---
Title: "**Voting in Crisis: Analyzing the Impact of COVID-19 on the 2020 Election in New York State**"
output: 
  html_document:
    toc: true
    toc_float: true
---

### **Demographic and Voting Data**
* `state` : Name of the U.S. state for the corresponding data.

* `county` : Name of the county in New York State.

* `age_group` : Categorized age groups of voters ("18-24", "25-44", "45-64", "65+").

* `gender` : Gender of voters, either "Male" or "Female."

* `race` : Racial demographics of voters ("White", "Black", "Asian", "Hispanic", "Other").
education_level: Education attainment level of voters ("Less than High School", "High School Graduate", "Some College", "Bachelor's Degree or Higher").

* `income_bracket` : Income level of voters categorized by brackets ("<$25,000", "$25,000-$50,000", "$50,000-$75,000", ">$75,000").

* `voter_turnout` : Total number of voters who participated in the election within the demographic group.

* `total_population` : Total population of the demographic group.

* `percent_turnout` : Percentage of voters who participated in the election relative to the total population of the demographic group.

* `margin_of_error` : Statistical uncertainty for turnout estimates.


### **Socioeconomic Indicators**
* `poverty_rate` : Percentage of the population living below the poverty line.

* `median_household_income` : Median income of households in the state.

* `unemployment_rate` : Percentage of the labor force that is unemployed.

* `gini_index` : Measure of income inequality within the state (0 = perfect equality, 1 = maximum inequality).

* `healthcare_access_rate` : Percentage of residents with access to healthcare services.

### **Health Facilities**
* `facility_name` : Name of the health facility.

* `facility_type` : Type of the facility (value is either "Hospital," "Clinic" or "Urgent Care").

* `latitude` : Latitude coordinate of the facility's location. 

* `longitude` : Longitude coordinate of the facility's location.

* `bed_count` : Total number of beds available at the facility.

* `covid_capacity` : Capacity for treating COVID-19 patients.

* `staff_count` : Total number of healthcare staff employed.

### **Election Results**
* `candidate` : Name of the candidate in the 2020 election.

* `party` : Political party of the candidate (values is either "Democrat" or "Republican").

* `votes`: Total number of votes received by the candidate. 

* `percent_votes` : Percentage of total votes received by the candidate in the county.

* `absentee_votes` : Total number of absentee votes received by the candidate.

* `in_person_votes` : Total number of in-person votes received by the candidate.

### **COVID-19 Data**

* `cases` : Total number of confirmed COVID-19 cases in 2020.

* `deaths` : Total number of COVID-19-related deaths in 2020.

* `cases_per_100k` : COVID-19 cases per 100,000 residents.

* `deaths_per_100k` : COVID-19 deaths per 100,000 residents.

* `testing_rate` : Number of COVID-19 tests conducted per 100,000 residents.
