---
title: "Data"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(stringr)
```

```{r}
covid_19 = read.csv("data/New_York_State_Statewide_COVID-19_Testing__Archived__20241205.csv")
```

```{r}
covid_19_NY = filter(covid_19,
                     Test.Date == "11/03/2020" &
                       Geography == "COUNTY")
```

```{r}
covid_19_fatality = read.csv("data/New_York_State_Statewide_COVID-19_Fatalities_by_County_20241205.csv")
```

```{r}
covid_19_fatality_NY = filter(covid_19_fatality,
                     Report.Date == "11/03/2020")
```

```{r}
election_result = read.csv("data/election_result_NY_2020.csv")
```

```{r}
df = left_join(covid_19_NY, election_result,by = "County")
df = left_join(df, covid_19_fatality_NY, by = "County")
```

*Socioeconomic indicator---poverty
```{r}
#Load dataset
poverty_level <- read.csv("data/2000_socioeconomic_indicator_poverty.csv") %>%
  janitor::clean_names()
```


```{r}
#Extract the first column and use it as a dataframe
first_column <- data.frame(poverty_level$label_grouping)%>%
  filter(str_ends(poverty_level$label_grouping, "New York"))
```

```{r}
#keeping all estimate as a seprate dataframe
df <- poverty_level%>%
  filter(str_ends(label_grouping,"Estimate"))
```

```{r}
#Binding those two into one dataframe
poverty_county_level <- cbind(first_column, df) %>%
  mutate(
    total = as.numeric(gsub(",", "", total)),
    total_income_in_the_past_12_months_at_or_above_the_poverty_level = as.numeric(gsub(",", "", total_income_in_the_past_12_months_at_or_above_the_poverty_level)),
    total_income_in_the_past_12_months_below_poverty_level = as.numeric(gsub(",", "", total_income_in_the_past_12_months_below_poverty_level)),
    above_poverty_percentage = (total_income_in_the_past_12_months_at_or_above_the_poverty_level / total) * 100,
    below_poverty_percentage = (total_income_in_the_past_12_months_below_poverty_level / total) * 100
  ) %>%
  rename(
    county = poverty_level.label_grouping
  ) %>%
  mutate(
    county = sub(" County, New York$", "", county)
  ) %>%
  select(-label_grouping)%>%
  slice(-1) 
```



*2020 voting demographic---age
```{r}
#load the dataset
voting_age <- read_csv("data/2000_voting_demographic_age.csv")%>%
  janitor::clean_names()
```

```{r}
#Extract the first column and use it as a dataframe
first_column_age <- data.frame(voting_age$label_grouping)%>%
  filter(str_ends(voting_age$label_grouping, "New York"))%>%
   rename(
    county = voting_age.label_grouping
  ) %>%
    mutate(
    county = sub(" County, New York$", "", county))
```

```{r}
#keeping all estimate as a seprate dataframe

df_age <- voting_age%>%
  filter(str_ends(label_grouping,"Estimate"))%>%
  mutate(
    total_18_to_29_years = as.numeric(gsub(",", "",total_18_to_29_years)),
    total_30_to_44_years = as.numeric(gsub(",", "",total_30_to_44_years)),
    total_45_to_64_years = as.numeric(gsub(",", "",total_45_to_64_years)),
    total_65_years_and_over = as.numeric(gsub(",", "",total_65_years_and_over)),
    total = as.numeric(gsub(",", "",total)))%>%
  mutate(
    below_30_percent = (total_18_to_29_years)/total*100,
    above_30_percent = (total_30_to_44_years+total_45_to_64_years+total_65_years_and_over)/total*100,
    above_65_percent = total_65_years_and_over/total*100)
```

```{r}
#Binding those two into one dataframe
voting_age_county_level <- cbind(first_column_age, df_age)%>%
  slice(-1)
```

