---
title: "Model of Republician voting rate"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r, echo = FALSE,message= FALSE, warning = FALSE}
library(tidyverse)
library(readxl)
library(modelr)
library(mgcv)
library(broom)
```

```{r, echo = FALSE}
election_covid = read.csv("data/voting_covid_detail.csv")
age = read_excel("data/voting_age_county_level_clean_v2.0.xlsx")
poverty = read_excel("data/poverty_county_level__clean_v2.0.xlsx")
hospitals = read_excel("data/2020_health_facility_count.xlsx")
names(election_covid)[names(election_covid)=="County"] <- "county"
```

```{r, echo = FALSE}
final_data = list(election_covid,age,poverty,hospitals)
final_data = final_data %>% reduce(left_join, by = "county")
```


### Linear model of Trump without Covid factor

```{r,message= FALSE, warning = FALSE}
model1 = lm(republician_percent~below_poverty_percentage+below_30_percent+above_65_percent+count, data = final_data)

model1_data <- final_data |>
  add_predictions(model1) |>
  add_residuals(model1)

ggplot(model1_data, aes(x = pred, y = resid)) +
  geom_point(alpha = 0.2) +
  labs(title = "Predict compare to residuls without considering Covid",
       x = "Predict value",
       y = "residuals value") +
  geom_smooth()
```

### Linear model of Trump with Covid factor
```{r,message= FALSE, warning = FALSE}
model2 = lm(republician_percent~below_poverty_percentage+below_30_percent+above_65_percent+count+Test_Positive, data = final_data)

model2_data <- final_data |>
  add_predictions(model2) |>
  add_residuals(model2)

ggplot(model2_data, aes(x = pred, y = resid)) +
  geom_point(alpha = 0.2) +
  labs(title = "Predict compare to residuls when considering Covid",
       x = "Predict value",
       y = "residuals value")+
  geom_smooth()
```

### Comparasion of two model
```{r}
compare = crossv_mc(final_data, 100) |> mutate(train = map(train, as_tibble),
                                      test = map(test, as_tibble))

compare = compare |> mutate(
    model1 = map(train, \(df) lm(republician_percent~below_poverty_percentage+below_30_percent+above_65_percent+count, data = df)),
    model2 = map(train, \(df) lm(republician_percent~below_poverty_percentage+below_30_percent+above_65_percent+count+Test_Positive, data = df)),
    rmse_model1 = 
      map2_dbl(model1, test, \(mod, df) rmse(model = mod, data = df)),
    rmse_model2 = 
      map2_dbl(model2, test, \(mod, df) rmse(model = mod, data = df))
)

compare |> 
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") |> 
  mutate(model = fct_inorder(model)) |> 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```



